### ISSUE TITLE
Usage of ssh-key

### ISSUE THREAD

**Issue by sebek88** [gaddman/rundeck-getfile#1]
Hello,

I am looking for a way to copy back some generated files from jobs that run on remote nodes, exactly as mentioned in your readme. It does not matter, but the protocol being used at my case is SCP. My problem and my question is the following: 
Is there is a way to make getfile.sh script to work with ssh-key authentication method instead of password auth? I am refering to the -p $PASSWORD option/variable in the last line.

Thank you for any feedback.

**Comment by gaddman** [comment]
yeah, should be doable. Are you using a passphrase? If you wanted to have a crack at a PR (or just get your own copy working) then https://github.com/rundeck-plugins/openssh-node-execution/blob/master/contents/ssh-copy.sh should give some good ideas. Otherwise I'll look at it in the next week or two.

**Comment by sebek88** [comment]
I am not using a passphrase, no, just the ssh-key. Thank you for the reference, seems relevant. I will have a crack at it when there is time.

**Comment by gaddman** [comment]
Add support for SSH key auth in commit 69fd250c346b469aba583a494422c0302e12071c. Must be in key storage (not on disk) and doesn't support passphrase.
